# Initial transmit voltage [V]
tx_voltage: 50 # [V]
# constant gain, available range: [14, 54]
tgc_start: 48 # [dB]
# How many frames should be captured into internal buffer.
capture_buffer_size: 10
capture_folder: C:/Users/NDT/Desktop/data

sequence:
  # Assumed speed of sound [m/s]
  speed_of_sound: 5900
  # Transmit voltage [Hz]
  tx_frequency: 5000000
  rx_sample_range_start_us: 10 # [us]
  rx_sample_range_end_us: 31.5 # [us]