import io
from queue import Queue
from typing import List

import cv2
import matplotlib.pyplot as plt
import numpy as np
import param
from panel.reactive import ReactiveHTML

import gui4us.cfg.display as display_cfg
from gui4us.common import ImageMetadata
from gui4us.logging import get_logger
from gui4us.utils import get_free_port_for_address
from gui4us.view.env.displays.rtc import RTCServer

# TODO make the below configurable
plt.style.use("dark_background")


class Display2D(ReactiveHTML):
    host = param.String(default="localhost")
    port = param.Integer(default=0)
    display_name = param.String(default="Display2D")

    __javascript__ = [
        "content/connectToDisplay.js"
    ]
    # NOTE: width and height of the below node determines the final
    # dimensions of the image generated by the VTK display server
    _template = '<video id="display_2d" autoplay="true" playsinline="true" style="width: 100%; height: 100%; margin: 0 auto;"></video>'
    _scripts = {
        "render":
            "sessionURL = 'http://' + data.host + ':' + data.port; "
            "state.client = connectToDisplay(display_2d, {application: data.display_name, sessionURL: sessionURL})"
    }

    def __init__(
            self,
            cfg: display_cfg.Display2D,
            metadatas: List[ImageMetadata],
            **params):
        """
        :param metadatas: list of output metadata; metadata[i] corresponds to
            value[i] from the update method
        """
        super().__init__(**params)
        self.logger = get_logger(f"{type(self)}:{self.display_name}")
        self.cfg = cfg
        self.metadatas = metadatas
        self.vtk_inputs = []
        self.initial_arrays = []
        self.preprocessing_outputs = []
        self.settings = []
        self.setters = []
        self.current_dr_min = []
        self.current_dr_max = []
        self.vtk_main_img_actor = None
        if self.port == 0:
            self.port = get_free_port_for_address(self.host)
        self.data_queue = Queue()
        self.server = RTCServer(
            host=self.host, port=self.port, input_queue=self.data_queue
        )
        self.prepare(metadatas=metadatas, cfg=cfg)

    def start(self):
        self.server.start()
        self.logger.info(f"Server started at: http://{self.host}:{self.port}")

    def join(self):
        pass # TODO

    def prepare(
            self,
            metadatas: List[ImageMetadata],
            cfg: display_cfg.Display2D
    ):
        self.fig, self.ax = plt.subplots()
        self.canvases = []
        self.axes_bg = []
        self.layers = []  # Flatten list of layers.
        self.sampling_points = []

        extents = None
        if cfg.extents is not None:
            extents = cfg.extents

        axis_labels = None
        if cfg.ax_labels is not None:
            axis_labels = cfg.ax_labels

        for layer in cfg.layers:
            self.layers.append(layer)
            metadata: ImageMetadata = metadatas[layer.input.ordinal]
            imshow_params = {}
            input_shape = metadata.shape
            dtype = metadata.dtype

            # Extents.
            # TODO: verify if all image metadata have exactly the
            # same extents and ids
            if extents is None and metadata.extents is not None:
                extents = metadata.extents
            if extents is not None:
                extent_x, extent_y = extents
                matplotlib_extents = [extent_y[0], extent_y[1],
                                      extent_x[1], extent_x[0]]

            if axis_labels is None and metadata.ids is not None:
                axis_labels = metadata.ids
            if axis_labels is None:
                axis_labels = "", ""
            if metadata.units is not None:
                units = metadata.units
            else:
                units = "", ""

            ax_vmin, ax_vmax = None, None
            if layer.value_range is not None:
                ax_vmin, ax_vmax = layer.value_range
            self.ax.set_xlabel(self.get_ax_label(axis_labels[0], units[0]))
            self.ax.set_ylabel(self.get_ax_label(axis_labels[1], units[1]))
            cmap = layer.cmap
            init_data = np.zeros(input_shape, dtype=dtype)
            if len(input_shape) == 2:
                # 2D grayscale or some other array -- apply matplotlib
                # cmap to get the final image.
                imshow_params["cmap"] = cmap
            elif len(input_shape) == 3:
                # 3D -- RGB or RGBA
                # Check the last axis size
                if not input_shape[-1] in {3, 4}:
                    raise ValueError("2D layer image should be "
                                     "a 2D array or 3D array with "
                                     "the last axis of size 3 or 4.")
            else:
                raise ValueError("2D layer image should be "
                                 "a 2D array or 3D array with "
                                 "the last axis of size 3 or 4.")
            canvas = self.ax.imshow(
                init_data, vmin=ax_vmin, vmax=ax_vmax,
                extent=matplotlib_extents,
                interpolation="none",
                **imshow_params
            )
            self.canvases.append(canvas)
            self.sampling_points.append(None)
            self.axes_bg.append(self.fig.canvas.copy_from_bbox(self.ax.bbox))
        self.canvases[0].figure.tight_layout()
        self.n_canvases = len(self.canvases)

    def update(self, data):
        try:
            # Restore the background
            for ax_bg in self.axes_bg:
                self.fig.canvas.restore_region(ax_bg)
            # Draw
            for j in range(self.n_canvases):
                l = self.layers[j]
                d = data[l.input.ordinal]
                c = self.canvases[j]
                c.set_data(d)
                self.ax.draw_artist(c)
                j += 1
                self.fig.canvas.blit(self.ax.bbox)
            buf = io.BytesIO()
            self.fig.savefig(buf, format="png")
            buf.seek(0)
            image = np.asarray(bytearray(buf.read()), dtype=np.uint8)
            image = cv2.imdecode(image, 1)
            self.server.send(image)
        except Exception as e:
            self.logger.exception(e)

    def get_settings(self):
        return self.settings

    def get_setters(self):
        return self.setters

    def get_ax_label(self, label, unit):
        label = f"{label}"
        if unit:
            label = f"{label} [{unit}]"
        return label
