from queue import Queue
from typing import List
import time
import matplotlib.pyplot as plt

import numpy as np
import param
import vtk
from panel.reactive import ReactiveHTML

import gui4us.cfg.display as display_cfg
from gui4us.common import ImageMetadata
from gui4us.logging import get_logger
from gui4us.utils import get_free_port_for_address
from gui4us.view.env.displays.vtk import (
    VTKDisplayServer, VTKDisplayServerOptions
)
from gui4us.view.env.displays.rtc import RTCServer
from .utils import to_vtk_image_data, convert_from_named_to_vtk_cmap
from gui4us.model.core import SettingDef, SetAction, Box
import io
import cv2


class Display2D(ReactiveHTML):
    host = param.String(default="localhost")
    port = param.Integer(default=0)
    display_name = param.String(default="Display2D")

    __javascript__ = [
        "content/connectToDisplay.js"
    ]
    # NOTE: width and height of the below node determines the final
    # dimensions of the image generated by the VTK display server
    _template = '<video id="display_2d" autoplay="true" playsinline="true" style="width: 50%; height: 50%; margin: 0 auto;"></video>'
    _scripts = {
        "render":
            "sessionURL = 'ws://' + data.host + ':' + data.port; "
            "state.client = connectToDisplay(display_2d, {application: data.display_name, sessionURL: sessionURL})"
    }

    def __init__(
            self,
            cfg: display_cfg.Display2D,
            metadatas: List[ImageMetadata],
            **params):
        """
        :param metadatas: list of output metadata; metadata[i] corresponds to
            value[i] from the update method
        """
        super().__init__(**params)
        self.logger = get_logger(f"{type(self)}:{self.display_name}")
        self.cfg = cfg
        self.metadatas = metadatas
        self.vtk_inputs = []
        self.initial_arrays = []
        self.preprocessing_outputs = []
        self.settings = []
        self.setters = []
        self.current_dr_min = []
        self.current_dr_max = []
        self.vtk_main_img_actor = None
        if self.port == 0:
            self.port = get_free_port_for_address(self.host)
        self.data_queue = Queue()
        self.server = RTCServer(
            host=self.host, port=self.port, input_queue=self.data_queue
        )

    def start(self):
        self.server.start()
        self.logger.info(f"Server started at: ws://{self.host}:{self.port}")

    def join(self):
        pass # TODO

    def _create_pipeline(
            self,
            metadatas: List[ImageMetadata],
            cfg: display_cfg.Display2D
    ):
        pass # TODO

    def update(self, data):
        # TODO avoid creating figure every time
        plt.figure()
        for d in data:
            plt.imshow(d)
        buf = io.BytesIO()
        plt.savefig(buf, format="png")
        buf.seek(0)
        image = np.asarray(bytearray(buf.read()), dtype=np.uint8)
        image = cv2.imdecode(image, 1)
        plt.close()
        self.server.send(image)

    def get_settings(self):
        return self.settings

    def get_setters(self):
        return self.setters
